### ISSUE TITLE
Augmented Lagrangian

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/JSOSolvers.jl#1]
Create A. L. using TRON

Was https://github.com/JuliaSmoothOptimizers/SolverTools.jl/issues/84

**Comment by abelsiqueira** [comment]
@egmara

**Comment by abelsiqueira** [comment]
Being implemented here: https://github.com/Egmara/Augmented-Lagrangian

**Comment by dpo** [comment]
Close this?
