### ISSUE TITLE
If there is a way to obtain the optimization trace of x values?

### ISSUE THREAD

**Issue by liuyxpp** [JuliaSmoothOptimizers/JSOSolvers.jl#112]
In Optim.jl, we can set `store_trace=true` and `extended_trace=true`. Then we can obtain x trace after optimization by

```julia
Optim.x_trace(result)
```

where `result` is the return value of `Optim.optimize(...)`.

The x trace, even better f trace and g trace, is useful to study the performance of the algorithm for the optimization problem.

**Comment by dpo** [comment]
callbacks are now in place in all solvers.
