### ISSUE TITLE
[trunk/QuasiNewtonModel] wrong `∇fn` at first iterate

### ISSUE THREAD

**Issue by paraynaud** [JuliaSmoothOptimizers/JSOSolvers.jl#175]
`∇fn` is not set to a particular value before the algorithm reaches the point where a QuasiNewtonModel is updated at the first iterate
```julia
if isa(nlp, QuasiNewtonModel)
  ∇fn .-= ∇f
  ∇fn .*= -1 
  push!(nlp, s, ∇fn)
  ∇fn .= ∇f
end
```
As a consequence`∇fn` value is the same as `∇f` instead of $y = \nabla f(x_{k+1}) - \nabla f(x_k)$.
I tried `∇fn == ∇f` righ before the push, and I obtained `true`.
This statement only apply to the first iterate.

For the other iterates, `∇fn .= ∇f` paired with the two lines`∇fn .-= ∇f; ∇fn .*= -1  # = ∇f(xₖ₊₁) - ∇f(xₖ)`  at the next iterate manage `∇fn` correctly (from the `if ... end` block above).

I suggest to introduce `∇fn .= ∇f` before the start of the loop.

**Comment by dpo** [comment]
> As a consequence∇fn value is the same as ∇f

It's worse; it contains garbage!

> I suggest to introduce ∇fn .= ∇f before the start of the loop.

That's the correct solution. Please open a pr.

Thanks!

**Comment by paraynaud** [comment]
```julia
It's worse; it contains garbage!
```
My test passed because I tried it on a `TrunkSolver` dedicated to `PartitionedVector`.
I applied `∇fn.=0` in `TrunkSolver`'s definition to fix the reproductibily issue I had, in my case `∇fn` was not undef.
