### ISSUE TITLE
Compare TRON's trust region with basic trust region

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/JSOSolvers.jl#2]
Perhaps `trunk` could also use TRON's slightly more elaborate trust-region.

Was https://github.com/JuliaSmoothOptimizers/SolverTools.jl/issues/79

**Comment by dpo** [comment]
Here are the profiles on all 240 unconstrained problems from CUTEst.

### All problems together
![all](https://user-images.githubusercontent.com/38760/64463970-1118e880-d0d4-11e9-8078-7c12dfaec3f2.png)

### Small problems (n ≤ 100)
![small](https://user-images.githubusercontent.com/38760/64464005-33126b00-d0d4-11e9-8b75-82f17bbcdc3f.png)

### Medium problems (100 < n ≤ 1,000)
![medium](https://user-images.githubusercontent.com/38760/64464025-4c1b1c00-d0d4-11e9-984a-2599d3db4ddb.png)

### Large problems (1,000 < n ≤ 10,000)
![large](https://user-images.githubusercontent.com/38760/64464075-72d95280-d0d4-11e9-8e9f-9d7af98ef6e6.png)

### Extra large problems (10,000 < n)
![xlarge](https://user-images.githubusercontent.com/38760/64464232-39edad80-d0d5-11e9-811d-49b978097ef4.png)

ps: legend placement could really be improved!

**Comment by dpo** [comment]
The legend placement says `:bottomright` but that doesn't exactly seem to be working... https://github.com/JuliaSmoothOptimizers/SolverBenchmark.jl/blob/master/src/profiles.jl#L66

**Comment by abelsiqueira** [comment]
I believe we did this.
