### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/JSOSolvers.jl#20]
List of topics for docs:
- [x] Tutorial (https://jso.dev/tutorials/introduction-to-jsosolvers/)
- [x] Example for each solver
- [x] Usage of different subsolvers (trunk and tron nls) https://jso.dev/tutorials/advanced-jsosolvers/
- [x] Usage of NLP variant on NLS problems (trunk and tron) https://jso.dev/tutorials/introduction-to-jsosolvers/
- [x] Update docstrings (see #100)

**Comment by tmigot** [comment]
Connected to this, we could upgrade the docstring of each solver.
I suggested a first one for `trunk` #100 .

**Comment by abelsiqueira** [comment]
That's a great idea.
