### ISSUE TITLE
TRON: add a warning if initial guess is not within the bounds

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/JSOSolvers.jl#244]
I noticed we don't projet the initial guess, so if `verbose>0` we should probably send some warning

**Comment by Jay-sanjay** [comment]
@tmigot sir is it fine if, I add a condition in the 
`  if verbose > 0
    error("Invalid input")
  end`

**Comment by tmigot** [comment]
Thanks for thé suggestion @Jay-sanjay 
I think it should be a warning not an error and it only concerns TRON and TRON-NLS as they are the only handling bounds.

The warning message could be : Initial guess is not within bounds.

**Comment by dpo** [comment]
Also, the projection should happen.
