### ISSUE TITLE
Issue with the update of NLPModelsModifiers#v0.7.0

### ISSUE THREAD

**Issue by farhadrclass** [JuliaSmoothOptimizers/JSOSolvers.jl#258]
Since we have NLPModelsModifiers version 0.7.0
I want to update it but JSOsolver is blocking me because of this line :

https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/f52b678a5f9060709cd9aceb5d8749844755906d/Project.toml#L20

**Comment by farhadrclass** [comment]
@dpo here is the issue

**Comment by tmigot** [comment]
@farhadrclass Can we close this?
