### ISSUE TITLE
Negative predicted reduction in tron/trunk

### ISSUE THREAD

**Issue by tcovert** [JuliaSmoothOptimizers/JSOSolvers.jl#266]
Hi JSO team,

What should I infer about my problem and/or its suitability for use with `tron`/`trunk` if I encounter solution status equal to `:neg_pred`?

The problem I am solving is unconstrained, and is definitely not globally convex (I am trying to minimize the negative log likelihood of a nested logit model).  `lbfgs` does seem to "work" in the sense that if I give it a reasonable amount of time, it finds a reasonable fit (though I've yet to run it long enough to see if it converges).   Is the failure mode I am encountering with `tron` and `trunk` telling me something about the structure of my problem?  That I have perhaps a bug in my log-likelihood definition?  Or something else?

When I solve a simpler non-convex problem using similar data ("vanilla" logit, but with scale parameters that vary across choice sets, this heterogeneity I believe makes the problem non-convex), both `tron` and `trunk` seem to work great.  So I'm scratching my head about my nested logit setup...

Thanks in advance for any advice you might have.

**Comment by tcovert** [comment]
If it helps, I'm using autodiff (Zygote for gradients, and ForwardDiff over Zygote for the hessian-vector product).

**Comment by tmigot** [comment]
Hi  @tcovert ! Thanks for the issue 
Is there any chance you have a reproducible example?

**Comment by tcovert** [comment]
Sorry, I realized this was a bug in my autodiff implementation (I had written an incorrect custom adjoint), not an issue with the solver.  My bad.
