### ISSUE TITLE
Integrating a preconditioner into Trunk's trust-region subsolver

### ISSUE THREAD

**Issue by mpf** [JuliaSmoothOptimizers/JSOSolvers.jl#278]
I'm considering adding functionality to allow users to pass a preconditioner into Trunk's trust-region subsolver and would appreciate some guidance before I begin making changes.

## Options for Passing the Preconditioner

There seem to be at least two options here:

1. **Modify `SolverCore.solve!`:** Introduce a new keyword argument `M=I` in [`SolverCore.solve!`](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/38123a87443ce3255975441591f95513bb71bb1b/src/trunk.jl#L132) and pass it directly to [`Krylov.solve!`](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/38123a87443ce3255975441591f95513bb71bb1b/src/trunk.jl#L233-L243). This approach is straightforward and would allow updating the preconditioner with the latest iterate just before the call to `Krylov.solve!`.

2. **Use a Custom `CgSolver`:** Pass in to [`trunk`](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/38123a87443ce3255975441591f95513bb71bb1b/src/trunk.jl#L121)  a custom `CgSolver` that includes the preconditioner. I'm not sure of the details here, particularly how the preconditioner would be updated at each iteration.

The first approach seems simpler and more direct.

## Modifying Step-to-the-Boundary Calculation

As highlighted by @amontoison in this [Krylov.jl issue](https://github.com/JuliaSmoothOptimizers/Krylov.jl/issues/686#issue-1450450387), the step-to-the-boundary computation in [`to_boundary`](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/b5bb89aa3c635898ec18ed88fecf1f9d5ebb862c/src/krylov_utils.jl#L393) needs updating to solve the equation

    ‖x + σd‖_M = radius

where `‖v‖_M^2 = v'Mv`. This modification requires changes to both the `to_boundary` function and the corresponding call in [`cg.jl`](https://github.com/JuliaSmoothOptimizers/Krylov.jl/blob/b5bb89aa3c635898ec18ed88fecf1f9d5ebb862c/src/cg.jl#L215):

    σ = radius > 0 ? maximum(to_boundary(n, x, p, radius, dNorm2=pNorm²)) : α

Any advice or suggestions on these approaches would be greatly appreciated.

Thanks!

**Comment by amontoison** [comment]
Hi @mpf!

The best solution is `1.`, Krylov.jl already provides a way to change preconditioner at each call of a Krylov method.
We just need to make it possible to provide a preconditioner from a solver here in `JSOSolvers.jl`.

For the function `to_boundary`, I wanted to limit the number of  products with `M`.
The simplest solution is to perform three products with `M` to compute `‖d‖_M`, `xᴴMd` and `‖x‖_M`.
Can we do better?

**Comment by mpf** [comment]
> For the function `to_boundary`, I wanted to limit the number of products with `M`. The simplest solution is to perform three products with `M` to compute `‖d‖_M`, `xᴴMd` and `‖x‖_M` at each iteration. Can we do better?

Would it be possible to get away with only 2 products with `M`? Note

    ||x + σd‖²_M = σ² (d'Md) + σ (x'Md) + (x'Mx) = σ² (d'v) + σ (x'v) + (x'w),

where `v:=Md` and `w:=Mx`.

**Comment by amontoison** [comment]
I think it's optimal with 2 products with `M`. :+1: 
Michael, I will go to SIAM LA24 next week but I can add the support for a preconditioner `M`  in the function `to_boundary` when I will be back to Montréal.
