### ISSUE TITLE
Uniform input

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/JSOSolvers.jl#3]
We have to decide the input.

Suggestion:
- `max_f` or `max_eval`: Number of function evaluations (`neval_obj` or `sum_counters`?). Default: multiple of `nvar`.
- `max_iter`: Number of iterations. Default: -1 (no limit).
- `max_time`: Maximum elapsed time. Default: 30.0

Opinions

**Comment by dpo** [comment]
I'm not sure `max_iter` is a meaningful stopping condition. The work per iteration can vary widely from one method to another. I would suggest

* `max_eval` to mean the maximum sum of the number of evaluations of the objective and constraints (default -1 sounds good);
* `max_time` (default 30 sounds good).

**Comment by abelsiqueira** [comment]
Related to a discussion in #113, we could have a `Criteria`/`Conditions` structure to keep stopping conditions and have something like `status = get_status(nlp, output, criteria)` where the `output` is being updated inside the iterations.
I am not sure how that structure would be, but the basic idea would be to replace kwargs.

**Comment by dpo** [comment]
done? @tmigot

**Comment by tmigot** [comment]
What is uniform?
### Verbosity
- [X] logging
- [X] verbose
- [X] verbose as an integer
### Callback
- [X] callback function
### Kwargs
- [ ] `x::V` (default nlp.meta.x0) -- all except R2 where it is `x0`
- [X] `ato::T` (default `√eps(T)`)
- [X] `rtol::T` (default `√eps(T)`)
- [X] `max_eval::Int` (default `-1`)
- [ ] `max_time::Float64` (default (`30.0`) -- except R2 where it is 3600.0

**Comment by dpo** [comment]
Let's use `x` everywhere. But it makes sense that a first-order method would have more time than a second-order method.
