### ISSUE TITLE
CITATION.bib

### ISSUE THREAD

**Issue by matbesancon** [JuliaSmoothOptimizers/JSOSolvers.jl#50]
What would be the best reference to cite this package? :)

**Comment by abelsiqueira** [comment]
Yes! We totally forgot to add the DOI for it on README and the corresponding CITATION.bib.
Here's the Zenodo: 10.5281/zenodo.3991143
We'll add a CITATION.bib shortly.

Also, depending on when you're publishing, we might have a technical report for JuliaSmoothOptimizers ;)

**Comment by dpo** [comment]
You’re not yet sure he’ll have positive things to say ;-)

**Comment by abelsiqueira** [comment]
A citation is a citation.
