### ISSUE TITLE
Conflict export `solve!` with Krylov.jl

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/JSOSolvers.jl#80]
In the breakage tests of `ADNLPModels.jl`, [for instance here](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/actions/runs/1095171407), we had the following error:
```
WARNING: both JSOSolvers and Krylov export "solve!"; uses of it in module Main must be qualified
LBFGS: Error During Test at /home/runner/work/ADNLPModels.jl/ADNLPModels.jl/JSOSolvers.jl/test/allocs.jl:33
  Got exception outside of a @test
  UndefVarError: solve! not defined
```
Since, `JSOSolvers.jl` uses `Krylov.jl`, should it import it maybe?

**Comment by abelsiqueira** [comment]
Yes, the Krylov.jl update broke JSOSolvers, so we need to update with an import. Should be easy, but I haven't found the time to do it yet.

**Comment by abelsiqueira** [comment]
:pray:
