### ISSUE TITLE
LBFGS: The mem parameter can have a higher value than the number of variables

### ISSUE THREAD

**Issue by MonssafToukal** [JuliaSmoothOptimizers/JSOSolvers.jl#89]
I noticed that in `lbfgs`, it is possible to set the `mem` parameter to a higher value than necessary. For instance, if `nlp.meta.nvar  < mem`, then no error occurs. I am not sure if it impacts performance, but a small fix could be to replace the `mem = mem` with `mem =max(mem, nvar)` on line 32 of `lbfgs.jl`. Am I missing something? At least, it would guarantee no side effects.

**Comment by dpo** [comment]
It's allowed to set mem > nvar.
