### ISSUE TITLE
Bug: `gn` not defined in `tron`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/JSOSolvers.jl#93]
I noticed this error in [Percival.jl #82](https://github.com/JuliaSmoothOptimizers/Percival.jl/pull/82), when solving quasi-Newton model the variable `gn` is not defined on [L.187](https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/blob/7a491a8e3a0698b1f8e55c83ec3ece489a16006a/src/tron.jl#L187)

**Comment by dpo** [comment]
Just guessing that it got lost here: https://github.com/JuliaSmoothOptimizers/JSOSolvers.jl/commit/7cdb790e6931f2ba7f02604b4ced5c9a8f6d3da1#diff-68ea782c37a958a4cf4fd02b8c8f0d6273eb5558af23e93372be47d67b47f436L79
